### ISSUE TITLE
kubernetes-config repo

### ISSUE THREAD

**Issue by gitressa** [Obmondo/k8id#4]
I wanted to try K8id, and in the `README.md` it says:

> ## Setup of Kubernetes clusters
>
> Mirror this repo and the `kubernetes-config` repo into a Git platform of your choice [...]

https://github.com/Obmondo/k8id/blob/master/README.md#setup-of-kubernetes-clusters

Where can I find the `kubernetes-config` repo mentioned?

**Comment by KlavsKlavsen** [comment]
@gitressa Thank you for pointing this out.. We're pushing our template of this to a repo now and will link you once its there..
We've all been using this internally - so its "all too well understood" - so its good to get fresh eyes and perspectives, so we can improve :)

**Comment by gitressa** [comment]
Perfect @KlavsKlavsen, I look forward to trying it out. Thanks for making the project in the first place :)

**Comment by Aman1994** [comment]
Hi @gitressa , we have added the `k8id-config` repo now, you can find it here https://github.com/Obmondo/k8id-config. We have also updated the Readme of k8id to reflect the same https://github.com/Obmondo/k8id/blob/master/README.md#setup-of-kubernetes-clusters

**Comment by gitressa** [comment]
Thanks for fast reply and updates @Aman1994. I'll give it a spin as soon as I find time. Have a nice day.
